### ISSUE TITLE
Weird physics

### ISSUE THREAD

**Issue by NotLe0n** [bafto/Platformer#8]
- Moving to the Left is twice as slow as moving to the right.

**Comment by bafto** [comment]
The weird movement to the left is a known bug and worked on.
The jumping works perfectly fine for me tho.

**Comment by NotLe0n** [comment]
Did you fix the jumping?

**Comment by NotLe0n** [comment]
> Did you fix the jumping?

Ah nevermind I just saw #b1b7f0a7d4a25f074ed14b868c5ba9c168e7cea8

**Comment by bafto** [comment]
Fixed in commit 9c7c307. Now slightly new movement system (removed Lerp).
